### PR TITLE
Do extra header validation in table schema mode

### PR DESCRIPTION
**Pull request by stephent-stratdat**
The existing code just creates a csv header row from the parsed header fields, and one from the expected header fields and does a string compare. If they don't match it throws a single *warning*.

This patch adds extra validation to the provided headers:
* csv header not in the schema
  * `:unknown_header` error
* csv header found in the schema, but in the wrong column =>
  * `:known_header_wrong_column` error
* header in the schema, but not in the csv
  * `:missing_header error`

The `:malformed_header` warning behaviour is still as before

### CODE REVIEW

**Comment by stephent-stratdat** [comment]
Not sure if this is a good idea or not.

I definitely want this sort of validation, just not sure if this is the right place to add it.

**Comment by adamc00** [comment]
> I definitely want this sort of validation, just not sure if this is the right place to add it.

As in that this code is the wrong place to add it, or there might be a better place to add it in this code?

**Comment by sdt** [comment]
> > I definitely want this sort of validation, just not sure if this is the right place to add it.
> 
> As in that this code is the wrong place to add it, or there might be a better place to add it in this code?

The former. If this was just one of our own libraries, I'd be adding it here. It's just I'm not sure how this fits with PMHC or any other projects that might be using it.

Being in the table schema code path (vs csvw), I don't think it will affect them.

**Comment by stephent-stratdat** [comment]
Jeez I'm bad at having multiple identities...

**Comment by stephent-stratdat** [comment]
@veryrusty how do you feel about this one? Will it affect PMHC?

**Review by veryrusty — APPROVED** [review]
All good, doesn't impact PMHC in any way. Merge away!

When I get a chance I'll pull this into the csvw side of the csvlint code.

**Pull request merged**
